### ISSUE TITLE
HDHomeRun Start Not Working

### ISSUE THREAD

**Issue by stingray67** [uyorum/rpi-python-firetv#1]
Hello,

I was able to get every app on my firetv to open/start using the get command. HDHomeRun shows that the following process running:
"com.silicondust.view:hdhr_svc_proc"

When I send a get command to it, I receive a 403 error on my raspberry pi when sending request HTTP/1.1.  

I can open every other app. Any suggestions?

Thanks!

**Comment by uyorum** [comment]
Because other apps run correctly, this seems to be a problem of python-firetv or HDHomeRun.
I don't use HDHomeRun, and I have no idea.
Sorry.
